// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTmTransaction = "tm_transaction"

// TmTransaction mapped from table <tm_transaction>
type TmTransaction struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Date        time.Time `gorm:"column:date;not null" json:"date"`
	Description string    `gorm:"column:description;not null" json:"description"`
	AmountCents int32     `gorm:"column:amount_cents;not null" json:"amount_cents"`
	CategoryID  *string   `gorm:"column:category_id" json:"category_id"`
}

// TableName TmTransaction's table name
func (*TmTransaction) TableName() string {
	return TableNameTmTransaction
}
