// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"time"
)

type TmTransaction struct {
	ID          string    `json:"id"`
	Date        time.Time `json:"date"`
	Description string    `json:"description"`
	AmountCents int32     `json:"amountCents"`
	CategoryID  *string   `json:"categoryId"`
}

type TmTransactionCategory struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type TmTransactionClassifyingRule struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CategoryID  string `json:"categoryId"`
	RuleType    string `json:"ruleType"`
	Pattern     string `json:"pattern"`
}
