// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"time"
)

type TmTransaction struct {
	ID          string
	Date        time.Time
	Description string
	AmountCents int32
	CategoryID  *string
}

type TmTransactionCategory struct {
	ID          string
	Name        string
	Description string
}

type TmTransactionClassifyingRule struct {
	ID          string
	Name        string
	Description string
	CategoryID  string
	RuleType    string
	Pattern     string
}
