// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package data

import (
	"context"
	"time"
)

const addTransaction = `-- name: AddTransaction :execrows
insert into tm_transaction
  (id, date, description, amount_cents, category_id)
values ($1, $2, $3, $4, $5)
on conflict do nothing
`

type AddTransactionParams struct {
	ID          string    `json:"id"`
	Date        time.Time `json:"date"`
	Description string    `json:"description"`
	AmountCents int32     `json:"amountCents"`
	CategoryID  *string   `json:"categoryId"`
}

func (q *Queries) AddTransaction(ctx context.Context, db DBTX, arg AddTransactionParams) (int64, error) {
	result, err := db.Exec(ctx, addTransaction,
		arg.ID,
		arg.Date,
		arg.Description,
		arg.AmountCents,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTransactions = `-- name: ListTransactions :many
select id, date, description, amount_cents, category_id
from tm_transaction
where date >= $1 and date <= $2
order by date desc
`

type ListTransactionsParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date2"`
}

func (q *Queries) ListTransactions(ctx context.Context, db DBTX, arg ListTransactionsParams) ([]TmTransaction, error) {
	rows, err := db.Query(ctx, listTransactions, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TmTransaction
	for rows.Next() {
		var i TmTransaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.AmountCents,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
