// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package data

import (
	"context"
	"time"
)

const addTransaction = `-- name: AddTransaction :execrows
insert into tm_transaction
  (id, date, description, amount_cents, category_id)
values ($1, $2, $3, $4, $5)
on conflict do nothing
`

type AddTransactionParams struct {
	ID          string    `json:"id"`
	Date        time.Time `json:"date"`
	Description string    `json:"description"`
	AmountCents int32     `json:"amountCents"`
	CategoryID  *string   `json:"categoryId"`
}

func (q *Queries) AddTransaction(ctx context.Context, db DBTX, arg AddTransactionParams) (int64, error) {
	result, err := db.Exec(ctx, addTransaction,
		arg.ID,
		arg.Date,
		arg.Description,
		arg.AmountCents,
		arg.CategoryID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
